### PR TITLE
Add support for Samsung Pen Window and Multi Window

### PR DESCRIPTION
**Pull request by xdujiang**

### CODE REVIEW

**Comment by seven332** [comment]
Thanks for the new feature. But I don't own any Samsung phone. I can't test it.
Have you tested the feature? What does it works like? Could you tell me where I can get documents about the feature.

**Comment by xdujiang** [comment]
I have simply tested it, it can work on my Samsung NOTE3.

This is the Pen Window:
screenshot_2016-08-20-15-03-24

And this is Multi Window (the app below is QuickPic):
screenshot_2016-08-20-15-04-52

I followed a thread on XDA rather than the official document, but the document may be here:
http://developer.samsung.com/technical-doc/view.do?v=T000000144L

**Comment by seven332** [comment]
I checked the document, but I only found this line below.
`<meta-data android:name="com.samsung.android.sdk.multiwindow.penwindow.enable" android:value="true" />`
`com.samsung.android.sdk.multiwindow.penwindow.enable` looks different than others. I can't find any thing link com.sec.android.xxx.xxx.xxx in the document.

What about "com.samsung.android.sdk.multiwindow.enable" ?

**Comment by xdujiang** [comment]
有点没看懂...
河马先森我们还是用中文说吧...

**Comment by seven332** [comment]
我在文档里就看到了 `com.samsung.android.sdk.multiwindow.penwindow.enable`，其他的都没看到。

你试试只加上这个好不好使。
```
<meta-data android:name="com.samsung.android.sdk.multiwindow.enable" android:value="true" />
<meta-data android:name="com.samsung.android.sdk.multiwindow.multiinstance.enable" android:value="true" />
<meta-data android:name="com.samsung.android.sdk.multiwindow.penwindow.enable" android:value="true" />
```

**Comment by xdujiang** [comment]
好像可以诶...连那两个intent都不用加...我记得以前没那两个intent就不能在多窗口菜单显示的啊...

只加那三行好像就可以了，暂时没碰到什么毛病

**Comment by seven332** [comment]
那就再麻烦你提交一下

**Pull request closed without merging**
